"""testusertable change

Revision ID: 06f20ad30445
Revises: f918dce77f8b
Create Date: 2024-02-29 06:23:17.921950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f20ad30445'
down_revision: Union[str, None] = 'f918dce77f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_user', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_user', 'status')
    # ### end Alembic commands ###
