"""word model add tag  column

Revision ID: f918dce77f8b
Revises: 00fde96fb246
Create Date: 2024-02-29 06:17:10.931389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f918dce77f8b'
down_revision: Union[str, None] = '00fde96fb246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('tag', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_words_tag'), 'words', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_tag'), table_name='words')
    op.drop_column('words', 'tag')
    # ### end Alembic commands ###
